package cn.edu.fudan.se.clonedetector.bean;

// Generated 2016-5-20 10:49:33 by Hibernate Tools 3.4.0.CR1

/**
 * Author generated by hbm2java
 */
public class Author implements java.io.Serializable {

	private Integer authorId;
	private String authorNick;
	private String authorName;
	private Integer commitId;

	public Author() {
	}

	public Author(String authorNick, String authorName, Integer commitId) {
		this.authorNick = authorNick;
		this.authorName = authorName;
		this.commitId = commitId;
	}

	public Integer getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(Integer authorId) {
		this.authorId = authorId;
	}

	public String getAuthorNick() {
		return this.authorNick;
	}

	public void setAuthorNick(String authorNick) {
		this.authorNick = authorNick;
	}

	public String getAuthorName() {
		return this.authorName;
	}

	public void setAuthorName(String authorName) {
		this.authorName = authorName;
	}

	public Integer getCommitId() {
		return this.commitId;
	}

	public void setCommitId(Integer commitId) {
		this.commitId = commitId;
	}

}
