package cn.edu.fudan.se.clonedetector.bean;

// Generated 2016-5-20 10:49:33 by Hibernate Tools 3.4.0.CR1

/**
 * File generated by hbm2java
 */
public class ChangeFile implements java.io.Serializable {

	private Integer fileId;
	private String fileName;
	private Integer commitId;
	private byte[] content;
	private Integer loc;
	private Integer eloc;
	private Integer cloc;
	private Integer ecloc;
	private Integer chloc;
	private Integer echloc;
	private Integer compareId;
	private Integer changeFileId;
	// deleted clone code
	private Integer dcloc;
	private Integer edcloc;
	//black lines and comment lines
	private Integer bloc;
	private Integer cmloc;
	private Integer bcloc;
	private Integer cmcloc;
	private Integer bchloc;
	private Integer cmchloc;
	private Integer bdcloc;
	private Integer cmdcloc;
	
	private Integer aloc;
	private Integer ealoc;
	private Integer dloc;
	private Integer edloc;
	
	private Integer ccloc;
	private Integer eccloc;
	
	private String fileType;

	public ChangeFile() {
	}

	public ChangeFile(String fileName, Integer commitId, byte[] content) {
		this.fileName = fileName;
		this.commitId = commitId;
		this.content = content;
	}

	public Integer getFileId() {
		return this.fileId;
	}

	public void setFileId(Integer fileId) {
		this.fileId = fileId;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public Integer getCommitId() {
		return this.commitId;
	}

	public void setCommitId(Integer commitId) {
		this.commitId = commitId;
	}

	public byte[] getContent() {
		return this.content;
	}

	public void setContent(byte[] content) {
		this.content = content;
	}

	public Integer getLoc() {
		return loc;
	}

	public void setLoc(Integer loc) {
		this.loc = loc;
	}

	public Integer getEloc() {
		return eloc;
	}

	public void setEloc(Integer eloc) {
		this.eloc = eloc;
	}

	public Integer getCloc() {
		return cloc;
	}

	public void setCloc(Integer cloc) {
		this.cloc = cloc;
	}

	public Integer getEcloc() {
		return ecloc;
	}

	public void setEcloc(Integer ecloc) {
		this.ecloc = ecloc;
	}

	public Integer getCompareId() {
		return compareId;
	}

	public void setCompareId(Integer compareId) {
		this.compareId = compareId;
	}

	public Integer getChloc() {
		return chloc;
	}

	public void setChloc(Integer chloc) {
		this.chloc = chloc;
	}

	public Integer getEchloc() {
		return echloc;
	}

	public void setEchloc(Integer echloc) {
		this.echloc = echloc;
	}

	public Integer getChangeFileId() {
		return changeFileId;
	}

	public void setChangeFileId(Integer changeFileId) {
		this.changeFileId = changeFileId;
	}

	public Integer getDcloc() {
		return dcloc;
	}

	public void setDcloc(Integer dcloc) {
		this.dcloc = dcloc;
	}

	public Integer getEdcloc() {
		return edcloc;
	}

	public void setEdcloc(Integer edcloc) {
		this.edcloc = edcloc;
	}

	/**
	 * @return the bloc
	 */
	public Integer getBloc() {
		return bloc;
	}

	/**
	 * @param bloc the bloc to set
	 */
	public void setBloc(Integer bloc) {
		this.bloc = bloc;
	}

	/**
	 * @return the cmloc
	 */
	public Integer getCmloc() {
		return cmloc;
	}

	/**
	 * @param cmloc the cmloc to set
	 */
	public void setCmloc(Integer cmloc) {
		this.cmloc = cmloc;
	}

	/**
	 * @return the bcloc
	 */
	public Integer getBcloc() {
		return bcloc;
	}

	/**
	 * @param bcloc the bcloc to set
	 */
	public void setBcloc(Integer bcloc) {
		this.bcloc = bcloc;
	}

	/**
	 * @return the cmcloc
	 */
	public Integer getCmcloc() {
		return cmcloc;
	}

	/**
	 * @param cmcloc the cmcloc to set
	 */
	public void setCmcloc(Integer cmcloc) {
		this.cmcloc = cmcloc;
	}

	/**
	 * @return the bchloc
	 */
	public Integer getBchloc() {
		return bchloc;
	}

	/**
	 * @param bchloc the bchloc to set
	 */
	public void setBchloc(Integer bchloc) {
		this.bchloc = bchloc;
	}

	/**
	 * @return the cmchloc
	 */
	public Integer getCmchloc() {
		return cmchloc;
	}

	/**
	 * @param cmchloc the cmchloc to set
	 */
	public void setCmchloc(Integer cmchloc) {
		this.cmchloc = cmchloc;
	}

	/**
	 * @return the bdcloc
	 */
	public Integer getBdcloc() {
		return bdcloc;
	}

	/**
	 * @param bdcloc the bdcloc to set
	 */
	public void setBdcloc(Integer bdcloc) {
		this.bdcloc = bdcloc;
	}

	/**
	 * @return the cmdcloc
	 */
	public Integer getCmdcloc() {
		return cmdcloc;
	}

	/**
	 * @param cmdcloc the cmdcloc to set
	 */
	public void setCmdcloc(Integer cmdcloc) {
		this.cmdcloc = cmdcloc;
	}

	/**
	 * @return the ccloc
	 */
	public Integer getCcloc() {
		return ccloc;
	}

	/**
	 * @param ccloc the ccloc to set
	 */
	public void setCcloc(Integer ccloc) {
		this.ccloc = ccloc;
	}

	/**
	 * @return the eccloc
	 */
	public Integer getEccloc() {
		return eccloc;
	}

	/**
	 * @param eccloc the eccloc to set
	 */
	public void setEccloc(Integer eccloc) {
		this.eccloc = eccloc;
	}

	public String getFileType() {
		return fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

	public Integer getAloc() {
		return aloc;
	}

	public void setAloc(Integer aloc) {
		this.aloc = aloc;
	}

	public Integer getEaloc() {
		return ealoc;
	}

	public void setEaloc(Integer ealoc) {
		this.ealoc = ealoc;
	}

	public Integer getDloc() {
		return dloc;
	}

	public void setDloc(Integer dloc) {
		this.dloc = dloc;
	}

	public Integer getEdloc() {
		return edloc;
	}

	public void setEdloc(Integer edloc) {
		this.edloc = edloc;
	}

}
