package cn.edu.fudan.se.clonedetector.bean;

// Generated 2016-5-20 10:49:33 by Hibernate Tools 3.4.0.CR1

/**
 * Change generated by hbm2java
 */
public class Change implements java.io.Serializable {

	public static final int DELETE = 1;
	public static final int INSERT = 2;

	private Integer changeId;
	private Integer changeType;
	private Integer beginLine;
	private Integer endLine;
	private String changeFragment;
	private Integer commitId;
	private Integer preCommitId;
	private Integer fileId;
	private Integer oldFileId;
	private Integer compareId;
	private Integer echloc;
	private Integer bchloc;
	private Integer cmchloc;
	

	

	public Change() {
	}

	public Change(Integer changeType, Integer beginLine, Integer endLine, String changeFragment, Integer commitId,
			Integer fileId, Integer oldFileId) {
		this.changeType = changeType;
		this.beginLine = beginLine;
		this.endLine = endLine;
		this.changeFragment = changeFragment;
		this.commitId = commitId;
		this.fileId = fileId;
		this.oldFileId = oldFileId;
	}

	public Change(Integer changeType, Integer beginLine, Integer endLine, Integer commitId, Integer fileId,
			Integer oldFileId) {
		this.changeType = changeType;
		this.beginLine = beginLine;
		this.endLine = endLine;
		// this.changeFragment = changeFragment;
		this.commitId = commitId;
		this.fileId = fileId;
		this.oldFileId = oldFileId;
	}

	public Integer getChangeId() {
		return this.changeId;
	}

	public void setChangeId(Integer changeId) {
		this.changeId = changeId;
	}

	public Integer getChangeType() {
		return this.changeType;
	}

	public void setChangeType(Integer changeType) {
		this.changeType = changeType;
	}

	public Integer getBeginLine() {
		return this.beginLine;
	}

	public void setBeginLine(Integer beginLine) {
		this.beginLine = beginLine;
	}

	public Integer getEndLine() {
		return this.endLine;
	}

	public void setEndLine(Integer endLine) {
		this.endLine = endLine;
	}

	public String getChangeFragment() {
		return this.changeFragment;
	}

	public void setChangeFragment(String changeFragment) {
		this.changeFragment = changeFragment;
	}

	public Integer getCommitId() {
		return this.commitId;
	}

	public void setCommitId(Integer commitId) {
		this.commitId = commitId;
	}

	public Integer getPreCommitId() {
		return preCommitId;
	}

	public void setPreCommitId(Integer preCommitId) {
		this.preCommitId = preCommitId;
	}

	public Integer getFileId() {
		return this.fileId;
	}

	public void setFileId(Integer fileId) {
		this.fileId = fileId;
	}

	public Integer getOldFileId() {
		return this.oldFileId;
	}

	public void setOldFileId(Integer oldFileId) {
		this.oldFileId = oldFileId;
	}

	public Integer getCompareId() {
		return compareId;
	}

	public void setCompareId(Integer compareId) {
		this.compareId = compareId;
	}

	public Integer getEchloc() {
		return echloc;
	}

	public void setEchloc(Integer echloc) {
		this.echloc = echloc;
	}

	/**
	 * @return the bchloc
	 */
	public Integer getBchloc() {
		return bchloc;
	}

	/**
	 * @param bchloc the bchloc to set
	 */
	public void setBchloc(Integer bchloc) {
		this.bchloc = bchloc;
	}

	/**
	 * @return the cmchloc
	 */
	public Integer getCmchloc() {
		return cmchloc;
	}

	/**
	 * @param cmchloc the cmchloc to set
	 */
	public void setCmchloc(Integer cmchloc) {
		this.cmchloc = cmchloc;
	}
}