package cn.edu.fudan.se.clonedetector.bean;

// Generated 2016-5-20 10:49:33 by Hibernate Tools 3.4.0.CR1

/**
 * CloneClass generated by hbm2java
 */
public class CloneClass implements java.io.Serializable {

	private Integer cloneClassId;
	private Integer commitId;
	private Integer type;
	public CloneClass() {
	}

	public CloneClass(Integer commitId) {
		this.commitId = commitId;
	}

	public Integer getCloneClassId() {
		return this.cloneClassId;
	}

	public void setCloneClassId(Integer cloneClassId) {
		this.cloneClassId = cloneClassId;
	}

	public Integer getCommitId() {
		return this.commitId;
	}

	public void setCommitId(Integer commitId) {
		this.commitId = commitId;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}


	
	
}
