package cn.edu.fudan.se.clonedetector.bean;

// Generated 2016-5-20 10:49:33 by Hibernate Tools 3.4.0.CR1

/**
 * Clone generated by hbm2java
 */
public class Clone implements java.io.Serializable {

	private Integer cloneId;
	private Integer beginLine;
	private Integer endLine;
	private String cloneFragment;
	private Integer cloneSize;
	private Integer cloneType;
	private Integer fileId;
	private Integer cloneClassId;
	private Integer commitId;
	private Integer ecloc;
	private Integer bcloc;
	private Integer cmcloc;
	//’€À„¥˙¬Î
	private Integer ccloc;
	private Integer eccloc;
	
	private Integer repeatTime;

	public Clone() {
	}

	public Clone(Integer beginLine, Integer endLine, String cloneFragment, Integer cloneSize, Integer cloneType,
			Integer fileId, Integer cloneClassId, Integer commitId) {
		this.beginLine = beginLine;
		this.endLine = endLine;
		this.cloneFragment = cloneFragment;
		this.cloneSize = cloneSize;
		this.cloneType = cloneType;
		this.fileId = fileId;
		this.cloneClassId = cloneClassId;
		this.commitId = commitId;
	}

	public Integer getCloneId() {
		return this.cloneId;
	}

	public void setCloneId(Integer cloneId) {
		this.cloneId = cloneId;
	}

	public Integer getBeginLine() {
		return this.beginLine;
	}

	public void setBeginLine(Integer beginLine) {
		this.beginLine = beginLine;
	}

	public Integer getEndLine() {
		return this.endLine;
	}

	public void setEndLine(Integer endLine) {
		this.endLine = endLine;
	}

	public String getCloneFragment() {
		return this.cloneFragment;
	}

	public void setCloneFragment(String cloneFragment) {
		this.cloneFragment = cloneFragment;
	}

	public Integer getCloneSize() {
		return this.cloneSize;
	}

	public void setCloneSize(Integer cloneSize) {
		this.cloneSize = cloneSize;
	}

	public Integer getCloneType() {
		return this.cloneType;
	}

	public void setCloneType(Integer cloneType) {
		this.cloneType = cloneType;
	}

	public Integer getFileId() {
		return this.fileId;
	}

	public void setFileId(Integer fileId) {
		this.fileId = fileId;
	}

	public Integer getCloneClassId() {
		return this.cloneClassId;
	}

	public void setCloneClassId(Integer cloneClassId) {
		this.cloneClassId = cloneClassId;
	}

	public Integer getCommitId() {
		return this.commitId;
	}

	public void setCommitId(Integer commitId) {
		this.commitId = commitId;
	}

	public Integer getEcloc() {
		return ecloc;
	}

	public void setEcloc(Integer ecloc) {
		this.ecloc = ecloc;
	}

	/**
	 * @return the bcloc
	 */
	public Integer getBcloc() {
		return bcloc;
	}

	/**
	 * @param bcloc the bcloc to set
	 */
	public void setBcloc(Integer bcloc) {
		this.bcloc = bcloc;
	}

	/**
	 * @return the cmcloc
	 */
	public Integer getCmcloc() {
		return cmcloc;
	}

	/**
	 * @param cmcloc the cmcloc to set
	 */
	public void setCmcloc(Integer cmcloc) {
		this.cmcloc = cmcloc;
	}

	/**
	 * @return the ccloc
	 */
	public Integer getCcloc() {
		return ccloc;
	}

	/**
	 * @param ccloc the ccloc to set
	 */
	public void setCcloc(Integer ccloc) {
		this.ccloc = ccloc;
	}

	/**
	 * @return the eccloc
	 */
	public Integer getEccloc() {
		return eccloc;
	}

	/**
	 * @param eccloc the eccloc to set
	 */
	public void setEccloc(Integer eccloc) {
		this.eccloc = eccloc;
	}

	/**
	 * @return the repeatTime
	 */
	public Integer getRepeatTime() {
		return repeatTime;
	}

	/**
	 * @param repeatTime the repeatTime to set
	 */
	public void setRepeatTime(Integer repeatTime) {
		this.repeatTime = repeatTime;
	}


}
