package cn.edu.fudan.se.clonedetector.bean;

// Generated 2016-5-20 10:49:33 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Commit generated by hbm2java
 */
public class Commit implements java.io.Serializable {

	private Integer commitId;
	private String revisionId;// svn的版本号，cc的baseline，revisionId和preRevisionId都与svn的url或cc的baseline这些拉取配置有关
	private String preRevisionId;
	private Date commitDate;
	private String commitLog;
	private Integer authorId;
	private Integer projectId;
	private Integer fileNum;
	private Integer cloneFileNum;
	private Integer loc;
	private Integer eloc;
	private Integer cloc;
	private Integer ecloc;
	private Integer bloc;
	private Integer cmloc;
	private Integer bcloc;
	private Integer cmcloc;
	//折算代码
	private Integer ccloc;
	private Integer eccloc;
	
	private String commitCode;
	private String selfVersionId;//tag模式下svn发布版本的版本号，cc的发布版本号，是有业务意义的id
	
	private Date submitDate;
	private Date scanDate;
	private Date submitDoneDate;
	private Integer stage;
	public static final int FAILED = -1;
	public static final int WAIT = 0;
	public static final int ALL_FINISH = 1;
	public static final int START = ALL_FINISH+1;
	public static final int CHECKOUT_FINISH = START+1;
	public static final int FILE_A_FINISH = CHECKOUT_FINISH + 1;
	public static final int CCFINDER_FINISH = FILE_A_FINISH + 1;
	public static final int UPDATE_FILE_CLOC_FINISH = CCFINDER_FINISH + 1;
	
	private static final int MAX = UPDATE_FILE_CLOC_FINISH;

	public static final float FAILED_PERCENT = -1;
	public static final float WAIT_PERCENT = 0;
	public static final float ALL_FINISH_PERCENT = 1;
	public static final float START_PERCENT = (float)(START-ALL_FINISH)/MAX;
	public static final float CHECKOUT_FINISH_PERCENT = (float)(CHECKOUT_FINISH-ALL_FINISH)/MAX;
	public static final float FILE_A_FINISH_PERCENT = (float)(FILE_A_FINISH-ALL_FINISH)/MAX;
	public static final float CCFINDER_FINISH_PERCENT = (float)(CCFINDER_FINISH-ALL_FINISH)/MAX;
	public static final float UPDATE_FILE_CLOC_FINISH_PERCENT = (float)(UPDATE_FILE_CLOC_FINISH-ALL_FINISH)/MAX;
	public static final String[] STAGES = new String[]{
		"等待执行","已经完成","拉取文件","分析文件","克隆分析","统计数据","汇总数据","失败"
	};
	
	public Commit() {
	}

	public Commit(String revisionId, String preRevisionId, Date commitDate,
			String commitLog, Integer authorId, Integer projectId) {
		this.revisionId = revisionId;
		this.preRevisionId = preRevisionId;
		this.commitDate = commitDate;
		this.commitLog = commitLog;
		this.authorId = authorId;
		this.projectId = projectId;
	}
	
	public Commit(String revisionId, String preRevisionId, Date commitDate,
			String commitLog, Integer authorId, Integer projectId, String selfVersionId) {
		this.revisionId = revisionId;
		this.preRevisionId = preRevisionId;
		this.commitDate = commitDate;
		this.commitLog = commitLog;
		this.authorId = authorId;
		this.projectId = projectId;
		this.selfVersionId = selfVersionId;
	}

	public Integer getCommitId() {
		return this.commitId;
	}

	public void setCommitId(Integer commitId) {
		this.commitId = commitId;
	}

	public String getRevisionId() {
		return this.revisionId;
	}

	public void setRevisionId(String revisionId) {
		this.revisionId = revisionId;
	}

	public String getPreRevisionId() {
		return this.preRevisionId;
	}

	public void setPreRevisionId(String preRevisionId) {
		this.preRevisionId = preRevisionId;
	}

	public Date getCommitDate() {
		return this.commitDate;
	}

	public void setCommitDate(Date commitDate) {
		this.commitDate = commitDate;
	}

	public String getCommitLog() {
		return this.commitLog;
	}

	public void setCommitLog(String commitLog) {
		this.commitLog = commitLog;
	}

	public Integer getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(Integer authorId) {
		this.authorId = authorId;
	}

	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	public Integer getFileNum() {
		return fileNum;
	}

	public void setFileNum(Integer fileNum) {
		this.fileNum = fileNum;
	}

	public Integer getLoc() {
		return loc;
	}

	public void setLoc(Integer loc) {
		this.loc = loc;
	}

	public Integer getEloc() {
		return eloc;
	}

	public void setEloc(Integer eloc) {
		this.eloc = eloc;
	}

	public Integer getCloc() {
		return cloc;
	}

	public void setCloc(Integer cloc) {
		this.cloc = cloc;
	}

	public Integer getEcloc() {
		return ecloc;
	}

	public void setEcloc(Integer ecloc) {
		this.ecloc = ecloc;
	}

	public Integer getCloneFileNum() {
		return cloneFileNum;
	}

	public void setCloneFileNum(Integer cloneFileNum) {
		this.cloneFileNum = cloneFileNum;
	}

	/**
	 * @return the bloc
	 */
	public Integer getBloc() {
		return bloc;
	}

	/**
	 * @param bloc the bloc to set
	 */
	public void setBloc(Integer bloc) {
		this.bloc = bloc;
	}

	/**
	 * @return the cmloc
	 */
	public Integer getCmloc() {
		return cmloc;
	}

	/**
	 * @param cmloc the cmloc to set
	 */
	public void setCmloc(Integer cmloc) {
		this.cmloc = cmloc;
	}

	/**
	 * @return the bcloc
	 */
	public Integer getBcloc() {
		return bcloc;
	}

	/**
	 * @param bcloc the bcloc to set
	 */
	public void setBcloc(Integer bcloc) {
		this.bcloc = bcloc;
	}

	/**
	 * @return the cmcloc
	 */
	public Integer getCmcloc() {
		return cmcloc;
	}

	/**
	 * @param cmcloc the cmcloc to set
	 */
	public void setCmcloc(Integer cmcloc) {
		this.cmcloc = cmcloc;
	}

	/**
	 * @return the ccloc
	 */
	public Integer getCcloc() {
		return ccloc;
	}

	/**
	 * @param ccloc the ccloc to set
	 */
	public void setCcloc(Integer ccloc) {
		this.ccloc = ccloc;
	}

	/**
	 * @return the eccloc
	 */
	public Integer getEccloc() {
		return eccloc;
	}

	/**
	 * @param eccloc the eccloc to set
	 */
	public void setEccloc(Integer eccloc) {
		this.eccloc = eccloc;
	}

	/**
	 * @return the commitCode
	 */
	public String getCommitCode() {
		return commitCode;
	}

	/**
	 * @param commitCode the commitCode to set
	 */
	public void setCommitCode(String commitCode) {
		this.commitCode = commitCode;
	}

	public String getSelfVersionId() {
		return selfVersionId;
	}

	public void setSelfVersionId(String selfVersionId) {
		this.selfVersionId = selfVersionId;
	}

	public Date getSubmitDate() {
		return submitDate;
	}

	public void setSubmitDate(Date submitDate) {
		this.submitDate = submitDate;
	}

	public Date getSubmitDoneDate() {
		return submitDoneDate;
	}

	public void setSubmitDoneDate(Date submitDoneDate) {
		this.submitDoneDate = submitDoneDate;
	}

	public Date getScanDate() {
		return scanDate;
	}

	public void setScanDate(Date scanDate) {
		this.scanDate = scanDate;
	}

	public Integer getStage() {
		return stage;
	}

	public void setStage(Integer stage) {
		this.stage = stage;
	}
	
}
